BeanUtilに、レコードを取り扱う機能を追加しました。
nablarch/nablarch-core-beans pull request #32
Opened 2024-02-21 02:10 UTC by tisuchida

# Mapからレコードを生成する機能の追加

`createAndCopy` メソッドで、パラメータMapからレコードを生成できるようにしました。
主な変更点は以下の通り。
* `createRecord` メソッド等、レコードを生成するメソッドの追加
* 既存の`setObjectProperty`メソッド等で、ネステッドプロパティがレコードだった場合の処理を追加
* プライベートメソッドのシグネチャ変更
    * 引数に `PropertyDescriptor` をとっていたメソッドについて、引数をプロパティ名に変更
        * `BeanUtil` では `PropertyDescriptors` 内部クラスで、`Introspector`を使用して`PropertyDescriptor`のキャッシュを作っているが、レコードクラスはこの方法では`PropertyDescriptor`を取得できないため。
        * `PropertyDescriptor`を渡す代わりに、プロパティ名を渡し、処理内で必要に応じて`PropertyDescriptor`を取得するように変更（`PropertyDescriptor`自体はキャッシュされているので、コストは増えない）
    * 引数にプロパティ値をとっていたメソッドについて、引数をパラメータMapに変更
        * レコードを生成する場合は、生成に必要なパラメータの全量が必要となる。
        * 既存のプログラムにもレコード生成処理を追加するため、引数でパラメータMapを渡す必要がある。
        * プロパティ値自体はパラメータMapから取得可能であるため、引数から削除した。

2024-02-22 08:32 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +        Map<String, Object> map = new HashMap<String, Object>() {
こっちはダイヤモンド演算子にしなくても警告は出ないのですか？（匿名クラスだと総称型は必要？）

2024-02-22 08:37 UTC, tishijiri commented on src/main/java/nablarch/core/beans/PropertyExpression.java
> +        this.rawKey = sj.toString();
`String.join(".", nestedProperties)`だけでもよさそうに見えたのですが、どうでしょうか。

2024-02-22 08:40 UTC, tishijiri commented on src/main/java/nablarch/core/beans/CopyOptions.java
> +        Collection<String> tmpExcludeProperties = excludesProperties.stream().map(pn -> pn.replace(propertyName + ".", "")).collect(Collectors.toCollection(HashSet::new));
ストリームのチェーンで1行が長くなりすぎてる気がしたので、改行したほうが読みやすいと思います（mapとcollectあたりで改行？）

2024-02-22 08:48 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +        Map<String, Object> map = new HashMap<String, Object>() {
警告が出ているのを見逃していました。
ダイヤモンド演算子に変更しました。合わせて、他で出ている警告にも対応しました。
2ed6a3cd368a330dffe5003b800c00beb26f0148

2024-02-22 08:50 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +        };
Java17になったので、Mapの初期化は`Map.of`使えばよいかなと思いました

2024-02-22 08:50 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilWithListAndArrayTest.kt
> +        System.out.println(actual)
消し忘れです。消去しました。
78dccbb2a5e1841550247038c678af8b2d292353

2024-02-22 08:53 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +            BeanUtil.createAndCopy(ItemRecord.class, map);
`assertThrows`使ったりtry-catch形式にしてたりするように見えたのですが、どっちでもよいなら`assertThrows`のがミスしづらそうな気がしました。

2024-02-22 08:53 UTC, tisuchida commented on src/main/java/nablarch/core/beans/PropertyExpression.java
> +        this.rawKey = sj.toString();
`String.join` の存在を知りませんでした。問題ないので変更しました。
e62628ec56b7a12446cdf747061fce701d709365

2024-02-22 08:55 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +    @SuppressWarnings("unused")
`ItemsForm`って同じクラスの後の方で参照していると思うんですが、警告出てるんでしょうか？

2024-02-22 08:55 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
>      public static class Item implements Serializable {
↑に同じ

2024-02-22 08:55 UTC, tisuchida commented on src/main/java/nablarch/core/beans/CopyOptions.java
> +        Collection<String> tmpExcludeProperties = excludesProperties.stream().map(pn -> pn.replace(propertyName + ".", "")).collect(Collectors.toCollection(HashSet::new));
修正しました。
f3fda99166313c6a9a6f3d4335ad07be70b741a9

2024-02-22 08:57 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    @SuppressWarnings("unchecked")
ここに限らずですが警告抑制は明確な理由が無い限り使うのは控えるべきだとは思えたんですが、ここはなんで必要なんでしょうか？

2024-02-22 08:59 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     * ただし、classプロパティは取得対象外となる。
概要とそれ以外の行は空白行を入れてほしいです。

2024-02-22 09:00 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     * ただし、classプロパティは取得対象外となる。
> classプロパティは取得対象外となる。

これがなぜなのかよくわからないので、Javadocには背景まで書いてあげた方がよいかと思いました。

2024-02-22 09:01 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    public static RecordComponent[] getRecordComponents(final Class<?> recordClass) {
`public`の必要があるのかわからなかったのですが、外から使われる想定なんでしょうか？

2024-02-22 09:04 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        return RecordComponents.get(recordClass).array;
`getPropertyDescriptor`との使い分けを教えてほしいのですが、レコードの場合はこっちを使うということなんでしょうか？それなら、それぞれで対応していない方のクラスを指定した場合の挙動をJavadocに明記したほうがよいかと思いました。（`getPropertyDescriptor`のJavadocも修正が必要ではないかなと思いました）

2024-02-22 09:07 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    public static RecordComponent getRecordComponent(final Class<?> recordClass, final String propertyName) {
全般的になんですが、新しいメソッドで引数に`final`つけなくてもよいのでは。

2024-02-22 09:09 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
クラスの説明が` JavaBeansに関する操作をまとめたユーティリティクラス。`となっているんですが、レコードはJavaBeansではないはずなので、ちょっと説明を加えた方がよいのではないかなと思いました。

2024-02-22 09:11 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            setProperty(nested, expression.rest(), getReducedMap(expression.getRoot(), map), copyOptions.reduce(propertyName));
このelseはBean処理に何か変更を加えてますか？

2024-02-22 09:13 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     *            プロパティの値をエントリーの値とするMap
`@param`の改行含めた文字列ってJavadoc上で想定通りの出力になってますか？

2024-02-22 09:14 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     * @return リスト、配列の要素の型
`BeansException`ってほかでは`@throw`で説明されてたようにも思ったので、どっちかに合わせたほうがよいかなと思いました。

2024-02-22 09:21 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        Object genericType = genericTypeParameter.getActualTypeArguments()[0];
固定で`[0]`を指定しているのが少し気になったので、これは確実に要素がある＆`0`インデックスのみ気にすればよいと思って大丈夫ですか？

2024-02-22 09:25 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    private static <T> T createRecord(Class<? extends T> beanClass, final Object srcBean, final CopyOptions copyOptions) {
ここだけJavadocが無い

2024-02-22 09:27 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            throw new BeansException(e);
ここだけ例外メッセージが設定されていないようです

2024-02-22 09:31 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        T recordInstance;
別の`createRecord`メソッドだとプロパティが無い場合のDEBUGログを出力していましたが、こちらは必要ない？

2024-02-22 09:37 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +                    : createInstance(propertyType);
Mapの`getOrDefault`メソッドとかでもよさそう

2024-02-22 09:38 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            propertyMap.put(propertyName, nested);
ここの上2行は`propertyMap`から`get`したときも呼ばれているようですが、どちらの場合でも必要な処理ですか？

2024-02-22 09:44 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    private static <SRC, DEST> DEST copyInner(final SRC srcBean, final DEST destBean, final CopyOptions copyOptions) {
可視性を落としていて後方互換に影響あるように見えるのですが、問題ないですか？

2024-02-22 09:57 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +        };
修正しました。
今回修正したテストクラスについては、合わせて同じ対応を実施しました。
65ec6b3edeac643fea7c9ac322630d7e449757c3

2024-02-22 09:58 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +        };
https://github.com/nablarch/nablarch-core-beans/commit/65ec6b3edeac643fea7c9ac322630d7e449757c3#diff-d6a23451a748c45f4b87acc8c2bb2cb0343aa6e0ac0076d8e2e300eece8def1dR45
については、「dateメソッドに同じ引数しか渡されていない」旨の警告への対応として変更したものです。

2024-02-22 10:03 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +            BeanUtil.createAndCopy(ItemRecord.class, map);
`assertThrows`に書き換えました。
ffe31345ac9d52d568923d4d23f969d5a84fdf15

2024-02-22 10:07 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +    @SuppressWarnings("unused")
setterで使用していない旨の警告が出ていましたが、範囲をクラスとしてしまっていました。
メソッドへの警告抑制に修正しました。
090e94f029ef2b26ae7bbbf271bf8b3865d2f44a

2024-02-22 10:08 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
>      public static class Item implements Serializable {
https://github.com/nablarch/nablarch-core-beans/pull/32#discussion_r1498990242
と同じ修正となります。

2024-02-26 01:45 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    @SuppressWarnings("unchecked")
当初、警告抑制以外に対応方法がないと考えていましたが、改めて見直したところ警告抑制せず対応可能であったため、警告抑制しない形に書き直しました。
1a7cb9685be136838acdb06b8597fce9b14c5b68

2024-02-26 01:50 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     * ただし、classプロパティは取得対象外となる。
既存のJavadocと合わせて修正しました。
73d7a363133e2f60abe5085a16062965399af66a

2024-02-26 02:20 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     * ただし、classプロパティは取得対象外となる。
当該記述は、`getPropertyDescriptors(..)`メソッドの記述をコピーした時の消し忘れのため、削除しました。
85e68485f7f5a214c956d3483adb9363964a8880

（補足）
`getPropertyDescriptors(..)`でプロパティ情報を取得する時、内部的には [`Introspector`](https://docs.oracle.com/javase/jp/17/docs/api/java.desktop/java/beans/Introspector.html)`.getBeanInfo(Class<?>)`を使用し、スーパークラスも含めて`BeanInfo`を検索します。
この時、`Object.getClass()`が`class`プロパティのゲッターとみなされてしまうため、結果の中に`class`の`PropertyDescriptor`が入り込んでしまうようです。
レコードについては、`getRecordComponents()`メソッドで直接コンポーネント情報を取得できるため、このようなことは発生しません。

2024-02-26 02:56 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        return RecordComponents.get(recordClass).array;
ご指摘のとおり、レコードの場合は上記メソッドを使用します。
使い分けのための情報をJavadocに記載するとともに、想定外の引数が来た場合に実行時例外とするよう修正しました。
1513030fb17580c57057bdee42dcefe15e0bd31f

2024-02-26 04:19 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    public static RecordComponent getRecordComponent(final Class<?> recordClass, final String propertyName) {
確かに不要のため、削除しました。
92ff95b4f2a01a4adf3cfd7d10d6a87b3b8e9f48

2024-02-26 04:23 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void 指定したトップレベル要素のみ使用してレコードを生成できること() {
トップレベル要素というのが何を指しているのかよくわからないのですが、一つ上のテストと何が違うのでしょうか？

2024-02-26 04:24 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilWithTypeParameterTest.java
> +        };
本体についても、同様の修正を実施しました。
1f46d5e8ee21a99542109933cba620a43bf5676b

2024-02-26 04:26 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +                Map.entry("sample", 10), // StringからIntegerへ変換できることも合わせて確認する
合わせて確認というのが中途半端（型変換はこのパターンだけでいいのか、StringからStringの単純な移送がテストされているのかパッと見てわからなかった）ので、ここは単純な設定のテストとして型変換はせず、別のテストで型変換を網羅できるようなテストにしておくのがよいように思ったのですが、どうでしょうか。

2024-02-26 04:28 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +                Map.entry("sample", 10), // StringからIntegerへ変換できることも合わせて確認する
（正直パッとみてどういうパターンをテストしているのかよくわからなかったので、私としてはパターンごとにテストケース分けるべきだとは思うのですが、これは既存のテストと合わせるようにしたからこの形なんでしょうか…）

2024-02-26 04:31 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +        String[] includeParamList = new String[] {
変数名はexcludeParamListの誤りかなと思いました

2024-02-26 04:34 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void MapからBeanに値を設定できること() {
テストケース名からはBeanのテストに思えて、BeanUtilTestでしているのと何が違うのだろうかと分からなかったのですが、なにかRecordが関係しているのでしょうか？

2024-02-26 04:41 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void Map内にプリミティブ型のコンポーネントに対応するパラメタが存在しない場合_デフォルト値で置換されること() {
このデフォルト値があるというのは、Beanの場合でもそういう仕様なので合わせてるんでしょうか？

2024-02-26 04:44 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +import static org.junit.Assert.*;
assertThatで警告出ていると思うので、他のテストと同じくHamcrestの方に変えたほうがよいのかな

2024-02-26 04:50 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void MapからBeanに値を設定できること() {
（この後にあるいくつかのテストも同じ）

2024-02-26 04:50 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void getRecordComponentsメソッドの引数にレコードを指定した場合_実行時例外が発生すること() {
Beanを指定した場合の間違い？

2024-02-26 04:50 UTC, tishijiri commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void getRecordComponentメソッドの引数にレコードを指定した場合_実行時例外が発生すること() {
Beanを指定した場合の間違い？

2024-02-26 04:52 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     * 指定したクラスから、特定プロパティの型を取得する。<br/>
`<br/>`は不要では。

2024-02-26 04:57 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            String rootPropertyWithDot = rootProperty + ".";
ネストのセパレータ`.`は他のクラスでも見たけど、バラバラに定義していても大丈夫そうです？（既存の実装でもそうのかな）

2024-02-26 05:00 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        }
これは一番最初に判定して変更不可な空Map（emptyMap()がいいのか？）を明示的に意図が分かりやすいと思います。

2024-02-26 05:07 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
>              // プリミティブ型の場合
`expression.isNode()`メソッドのJavadoc見るとプリミティブ型かどうかを判定するためのものではなさそうなのですが、これはコメント合ってるのでしょうか？

2024-02-26 05:16 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            }
LinkedHashMapじゃなくてもいいと思う（レコードコンポーネント名が被ることないと思うので）のと、↓でStream使っているならここもStreamでいいのではと思いました。

2024-02-26 05:17 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    private static <SRC, DEST> DEST copyInner(final SRC srcBean, final DEST destBean, final CopyOptions copyOptions) {
パッケージプライベートに修正しました。
b443bd426af14fb6f3599ddf5f979d292993cddc

2024-02-26 05:23 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        /** {@link PropertyDescriptor}の{@link Map}表現 */
レコードなのでPropertyDescriptorは間違っているかと思います。（他の箇所も同様）

2024-02-26 05:48 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +                    : createInstance(propertyType);
可能な箇所は、`Map`のAPIで置換しました。

c87cef411c5789e1730547ae894042dd9b9965bd
d9daa0fc7a1d5ec4a0c3eb97f51dc922ff817d32

2024-02-26 05:52 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
Javadocを修正しました。

f2f63237d134336bb57a3d7c70ba19a503da408a

2024-02-26 06:03 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     *            プロパティの値をエントリーの値とするMap
改行が単なる空白に置き換わっているので、記載を修正しました。
（参考）https://nablarch.github.io/docs/5u23/javadoc/nablarch/core/beans/BeanUtil.html#copy-java.lang.Class-T-java.util.Map-nablarch.core.beans.CopyOptions-

ccf8cea7a3080b6a19e05acb7c28ecd6ef43fc7e

2024-02-26 06:05 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    private static <T> T createRecord(Class<? extends T> beanClass, final Object srcBean, final CopyOptions copyOptions) {
Javadocを追加しました。

a876af4cbee999a43007281784f730edf1aae785

2024-02-26 07:13 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            propertyMap.put(propertyName, nested);
必要な処理となります。
`propertyMap`に格納されているJavaBeansは必ずしも構築済みではないため、`setProperty(..)`メソッドを使用して構築もしくは取得したJavaBeansを更新しています。

2024-02-26 07:37 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void Map内にプリミティブ型のコンポーネントに対応するパラメタが存在しない場合_デフォルト値で置換されること() {
明示されてはいないのですが、テストの挙動としてはそのようになっています。
テストに記載があるのは`int`型のみですが、
https://github.com/nablarch/nablarch-core-beans/blob/v6-develop/src/test/java/nablarch/core/beans/BeanUtilTest.java#L1075-L1080
で、`int`型のプロパティに該当する値が存在しない時、結果の値は`int`のデフォルト値となっています。

2024-02-26 07:42 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +import static org.junit.Assert.*;
2行上でhamcrestの`assertThat`はstatic importしているのですが、わかりづらいので展開しました。
4672054b6f17dce4cfa939175c171539db3a3eeb

2024-02-26 08:27 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     * @return リスト、配列の要素の型
既存のコードで記載されていない箇所も併せて記載しました。
e2e1d7e77fc58a05874d02ebd78dba2ef048ea1c

2024-02-26 08:48 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        Object genericType = genericTypeParameter.getActualTypeArguments()[0];
このメソッド自体は、`List`型のプロパティに対してのみ呼び出される前提です。
前段でパラメータ化された型であることをチェックしているため、当該行に到達する時点では、要素は空でなく、かつ`0`インデックスのみ見れば問題ありません。

本メソッドはレコード内のコンポーネントを対象としていますが、JavaBeansのプロパティを対象とした、同じ目的のメソッドである`getGenericType(..)`メソッド（既存メソッド）も、同様の判定をしています。

上記の点を踏まえ、前提事項をJavadocに記載しました。
併せて、既存メソッドのJavadocに不正確な点（配列プロパティにも使用するかのような記載があるが、配列プロパティにはこのメソッドを使用しない）があるので、そちらも修正しました。

ef23b539b9cd84a14edf5582eda1b3e73cb6c559

2024-02-26 10:18 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        return RecordComponents.get(recordClass).array;
全体的にJavadocを見直し、レコードが来た場合の記述を追加しました。
併せて、以下の対応を実施しました。
* レコードである/でない場合に実行時例外を送出する処理を、各メソッド毎ではなく共通メソッドに記載
* 不足していたテストを追加

0f475efb5af8cbe51506003172abe8b1b49bcc1c

2024-02-26 11:16 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void MapからBeanに値を設定できること() {
レコードは関係なく、今回修正した内容で既存のBean->Beanの処理も問題ないか、の観点でのテストでした。
すでに他のテストクラスで実施している、かつレコードに関係ない内容のため、当該テストを削除しました。

4a10bd751a47681d7d0917b5b97ef3b00e41e8b4

2024-02-26 11:18 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +        String[] includeParamList = new String[] {
誤りです。修正しました。
44c06b09265b68a9d9f8ca30b966b0d758c7c0c6

2024-02-26 11:19 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void getRecordComponentsメソッドの引数にレコードを指定した場合_実行時例外が発生すること() {
誤りです。修正しました。
0c3647c57e4b6e8a14a27e45cbad051e854a5440

2024-02-26 11:19 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void getRecordComponentメソッドの引数にレコードを指定した場合_実行時例外が発生すること() {
https://github.com/nablarch/nablarch-core-beans/pull/32#discussion_r1502445401
と同じです。

2024-02-26 11:25 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        }
指摘の通りと思います。修正しました。
1a59f033ce82a9ea0cd048b12933a8de95bdc2e2

2024-02-26 23:05 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        /** {@link PropertyDescriptor}の{@link Map}表現 */
修正しました。
a31b5fd925a72cf3e9984f429547e5ef80921378

2024-02-26 23:09 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
>              // プリミティブ型の場合
コメントが誤っています。
既存コード含め、修正しました。
1b436fbdc508114be5c867abf46177a9326246b1

2024-02-26 23:26 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +     * 指定したクラスから、特定プロパティの型を取得する。<br/>
不要な`<br/>`を削除しました。
併せて、javadocの表示がおかしくなっている箇所を修正しました。
d93e32dd5bd70c81a69b4818473b3d1d94ce4ec8

2024-02-26 23:41 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        T recordInstance;
[別の`createRecord`メソッド](https://github.com/nablarch/nablarch-core-beans/pull/32/files#diff-ae4a0a3a7e3dbfd0c00646653f8f18dbceb8c27e7e027011234c5f4bc0a840f7R686)では、ループ処理を生成先レコードの`RecordComponent`により実施しているため、生成元オブジェクトのプロパティが無い場合の検出ができず、明示的にDEBUGログを出力する必要がありました。
[こちらの`createRecord`メソッド](https://github.com/nablarch/nablarch-core-beans/pull/32/files#diff-ae4a0a3a7e3dbfd0c00646653f8f18dbceb8c27e7e027011234c5f4bc0a840f7R769)では、ループ処理を移送元Mapのエントリにより実施しているため、生成元のプロパティが無い場合には`BeansException`が送出され、結果としてDEBUGログが出力されます。

2024-02-26 23:49 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +    public void 指定したトップレベル要素のみ使用してレコードを生成できること() {
Mapの場合は、ネストしたプロパティを指定しても親プロパティを指定してもレコードを構築できることの確認をしたかったのですが、名前が分かりにくかったです。
テストケース名を変更しました。
9612937cae238390f3b59b7e99814d85ad5b1219

2024-02-26 23:52 UTC, tisuchida commented on src/test/java/nablarch/core/beans/BeanUtilForRecordTest.java
> +                Map.entry("sample", 10), // StringからIntegerへ変換できることも合わせて確認する
処理自体は他のテストで通っているので、念のため確認しておこう、くらいの意図で記載したものでした。
どちらかというとコンバータ関連のテストで実施すべきテストのため、コメントが余計でした。
コメント削除しました。
6af772281eb902488e95bd5928e00bd1c4325dd7

2024-02-27 01:02 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            String rootPropertyWithDot = rootProperty + ".";
`PropertyExpression`に処理を寄せることも検討しましたが、そのようにすると都度`new PropertyExpression(..)`する必要が出てきます。
これを避ける観点と、[解説書](https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/libraries/bean_util.html)やJavadocを見る限り、ネストのセパレータは`.`前提で変更する想定はなさそうに見えたので、これでもよいかなと思いました。

2024-02-27 01:48 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    public static RecordComponent[] getRecordComponents(final Class<?> recordClass) {
後方互換性の維持がつきまとってくるため、合わせて公開するより、必要ないなら公開すべきでないとは思いましたが、公開したほうがよさそうでしょうか？

2024-02-27 01:50 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            }
LinkedHashMapに変更するのもStreamで一緒にやればいいのではとおもったんですが、意図的ですか？

2024-02-27 02:08 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +                    : createInstance(propertyType);
キャッシュを操作しているところでも使えそうな気がしたので、一度見てみてください。

2024-02-27 02:47 UTC, tishijiri commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +        T recordInstance;
口頭で説明してもらったので、必要ない理由はわかりました。

2024-02-27 05:38 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            throw new BeansException(e);
例外メッセージが設定されていない箇所を確認し、あったほうがよさそうな箇所にはメッセージを追加しました。
3b7d61215a599b602fb1362c6f37e047c343753f

2024-02-27 06:06 UTC, tisuchida commented
@tishijiri 
`BeanUtilTest` の変更に伴い、インスペクションの警告対応を実施しました。
実施の中で、以下の対応も行っています。
* 使用していないプロパティへの警告抑制
* [（おそらく足りていなかった）テストの追加](https://github.com/nablarch/nablarch-core-beans/pull/32/files#diff-38ab6ea597c7e75146bb2dcd43df891f0a35be16a8e9dc39f47e316ae833fff6R1145)
* [解消できない`unchecked`警告の抑制](https://github.com/nablarch/nablarch-core-beans/pull/32/files#diff-38ab6ea597c7e75146bb2dcd43df891f0a35be16a8e9dc39f47e316ae833fff6R1254)
    * [参考](https://stackoverflow.com/questions/17679405/unchecked-generic-array-creation-for-varargs-parameter-of-type-matcher-exten)

2024-02-27 06:10 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +    public static RecordComponent[] getRecordComponents(final Class<?> recordClass) {
同等の機能は提供してもよいかな、程度の意図で、公開することのデメリットの方が大きいように思いますので、パッケージプライベートに変更しました。
5ccb1844841794ddb4aa6e136eeafeb7e566021a

2024-02-27 06:32 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +                    : createInstance(propertyType);
確認し、MapのAPIで置換可能な箇所を変更しました。
b0c556cedd5036289fb10911a728f5a34e552248

2024-02-27 07:28 UTC, tisuchida commented
@tishijiri 
レコードに関連したテストを、`BeanUtilForRecordTest`に集約しました。
36595df90109736a37e4bcab4e951022c3b2e9e3

2024-02-27 08:43 UTC, tisuchida commented
https://github.com/nablarch/nablarch-core-beans/pull/32#discussion_r1502032485
でMap→Beanのテストが不要、という指摘を受けましたが、
Beanのプロパティにレコードが含まれる場合の検証という観点で必要なテストであることを確認しました。
そのため、必要なテストのみ、メソッド名を変更して再度追加しました。

574f1da794759e938b2d8c3ca2d069220c52b94b

2024-02-27 08:45 UTC, tisuchida commented
@tishijiri 
`@Ignore`していたテストを修正しました。


491c12607e9a7f61c42d9a4ff4c6fe66c4c8b2bb

2024-02-27 11:47 UTC, kumagoro1202 requested changes

2024-02-28 00:52 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            throw new BeansException("corresponding property does not exist in the bean or record. property name: " + propertyName, e);
修正しました。
8be516026885b998cef13a58688976f6f3905bb4

2024-02-28 01:27 UTC, kumagoro1202 commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            throw new BeansException("corresponding property does not exist in the bean or record. property name: " + propertyName, e);
他とあわせて冠詞は入れるべきだと思います。
https://github.com/nablarch/nablarch-core-beans/pull/32/files#diff-ae4a0a3a7e3dbfd0c00646653f8f18dbceb8c27e7e027011234c5f4bc0a840f7R744

2024-02-28 01:34 UTC, tisuchida commented on src/main/java/nablarch/core/beans/BeanUtil.java
> +            throw new BeansException("corresponding property does not exist in the bean or record. property name: " + propertyName, e);
修正しました。
990ba30f6b989e0e2ccf21bfe814c28b1b28c01d

2024-02-28 01:36 UTC, kumagoro1202 approved these changes

2024-02-28 01:37 UTC, merged